"""Added ratings column to Feedback

Revision ID: 135f9a05bd5a
Revises: 9825773db1d3
Create Date: 2024-11-09 20:03:51.765517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135f9a05bd5a'
down_revision = '9825773db1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
