"""Fix relationships between Complaint and Feedback models

Revision ID: 39c18fff0245
Revises: d769471a0168
Create Date: 2024-11-07 16:50:16.065619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c18fff0245'
down_revision = 'd769471a0168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('feedback_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('feedback_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
