"""Added urgency column in complaint table

Revision ID: 564f7be67383
Revises: 5cc898ce76e7
Create Date: 2024-11-09 15:32:28.445924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564f7be67383'
down_revision = '5cc898ce76e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('urgency')

    # ### end Alembic commands ###
