"""Added sentiment column to Feedback

Revision ID: 9825773db1d3
Revises: 564f7be67383
Create Date: 2024-11-09 19:35:44.517812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9825773db1d3'
down_revision = '564f7be67383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
