"""Add assigned_employee_id to Complaint

Revision ID: b2447ae7c60f
Revises: 
Create Date: 2024-11-07 15:20:54.156248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'b2447ae7c60f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create a new table with the desired schema
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_employee_id', sa.Integer, nullable=True))
        batch_op.create_foreign_key(
            'fk_complaint_assigned_employee', 
            referent_table='user', 
            local_cols=['assigned_employee_id'], 
            remote_cols=['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_employee_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
