"""Added created_at column to Feedback

Revision ID: bf3dca77cbbe
Revises: 135f9a05bd5a
Create Date: 2024-11-09 20:14:17.155958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3dca77cbbe'
down_revision = '135f9a05bd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
