"""Update relationships between User, Complaint, and Feedback models

Revision ID: d769471a0168
Revises: b5858fecefd5
Create Date: 2024-11-07 16:35:06.440684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd769471a0168'
down_revision = 'b5858fecefd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('complaint_id', sa.VARCHAR(), nullable=False),
    sa.Column('feedback_text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.id'], name='fk_feedback_complaint_id'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
