"""Add assigned_employee_id to Complaint

Revision ID: f70f6884472a
Revises: b2447ae7c60f
Create Date: 2024-11-07 15:29:54.321776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70f6884472a'
down_revision = 'b2447ae7c60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
